# Generated by Django 4.2.7 on 2023-11-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='subscriptions',
            new_name='subscription',
        ),
    ]
